MedicalQuestions/Models/ErrorViewModel.cs
namespace MedicalQuestions.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MedicalQuestions/Controllers/AuthController.cs
using MedicalQuestions.Data;
using MedicalQuestions.Dto;
using MedicalQuestions.Data.Models;

using Microsoft.AspNetCore.Mvc;
using MedicalQuestions.Helpers;
using Microsoft.EntityFrameworkCore;
using MedicalQuestions.Services;
using MedicalQuestions.Email;
using MedicalQuestions.Email.Interfaces;

namespace MedicalQuestions.Controllers
{
    public class AuthController : BaseController
    {
        public MladostPublicContext DbContext { get; set; }
        public AuthService AuthService { get; set; }
        public IEmailSender EmailSender { get; set; }

        public AuthController(
            MladostPublicContext dbContext,
            AuthService authService,
            IEmailSender emailSender)
        {
            this.DbContext = dbContext;
            this.AuthService = authService;
            EmailSender = emailSender;
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (this.IsUserLoggedIn())
            {
                return this.RedirectToHomePage();
            }

            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginUserViewModel userModel)
        {
            User user = this.DbContext
                .Users
                .Include(x => x.Role)
                .FirstOrDefault(x => x.Username == userModel.Username);

            bool areCredentialsValid = this.AuthService.AreCredentialsValid(user, userModel.Password);

            if (areCredentialsValid)
            {
                this.HttpContext.Session.Set<string>("username", user.Username);
                this.HttpContext.Session.Set<string>("userRole", user.Role.Name);

                return this.RedirectToHomePage();
            }

            ViewBag.ShowError = true;
            return View();
        }

        public IActionResult Logout()
        {
            this.HttpContext.Session.Remove("username");
            this.HttpContext.Session.Remove("userRole");

            return this.RedirectToHomePage();
        }

        public IActionResult SignUp()
        {
            if (this.IsUserLoggedIn())
            {
                return this.RedirectToHomePage();
            }

            return View();
        }

        [HttpPost]
        public IActionResult DoSignUp(CreateProfileViewModel model)
        {
            string userPassword = this.AuthService.GeneratePassword();

            User user = new User
            {
                Username = this.AuthService.GenerateUniqueUsername(model.CompanyName),
                Password = BCrypt.Net.BCrypt.HashPassword(userPassword),
                RoleId = Common.Constants.UserRole.User
            };

            Profile profile = new Profile
            {
                CompanyName = model.CompanyName,
                PhysicalAddress = model.PhisicalAddress,
                EmailAddress = model.EmailAddress,
                ContactPerson = model.ContactPerson,
                Phone = model.Phone,
                EconomicSector = model.EconomicalSector,
                EmployeesCount = model.EmployeesCount,
                User = user
            };

            user.Profile = profile;

            string mailSubject = "Вашият профил е създаден";
            string mailBody = $"Използвайте потребителското име и парола по-долу за вход в системата. Потребителско име: {user.Username}, парола: {userPassword}";
            var message = new Message(model.EmailAddress, mailSubject, mailBody);
            this.EmailSender.SendEmail(message);

            this.DbContext.Users.Add(user);
            this.DbContext.Profiles.Add(profile);
            this.DbContext.SaveChanges();

            return Ok();
        }


        // todo: will be removed in prod
        public IActionResult Register()
        {
            return View();
        }

        // todo: will be removed in prod
        [HttpPost]
        public IActionResult DoRegister(LoginUserViewModel user)
        {
            string passwordHash = BCrypt.Net.BCrypt.HashPassword(user.Password);

            User dbUser = new User()
            {
                Username = user.Username,
                Password = passwordHash
            };

            DbContext.Users.Add(dbUser);
            DbContext.SaveChanges();

            return Ok();
        }
    }
}

MedicalQuestions/Controllers/BaseController.cs
using MedicalQuestions.Helpers;

using Microsoft.AspNetCore.Mvc;

namespace MedicalQuestions.Controllers
{
    public abstract class BaseController : Controller
    {
        protected IActionResult RedirectToHomePage()
        {
            return this.RedirectToAction("Index", "Home");
        }

        protected void AttachUserDataToViewBag()
        {
            string username = this.HttpContext.Session.Get<string>("username");
            string userRole = this.HttpContext.Session.Get<string>("userRole");

            if (!string.IsNullOrEmpty(username) && !string.IsNullOrEmpty(userRole))
            {
                ViewBag.IsUserLoggedIn = true;
                ViewBag.Username = username;
                ViewBag.UserRole = userRole.ToLower();
            }
        }

        protected bool IsUserLoggedIn()
        {
            string username = this.HttpContext.Session.Get<string>("username");

            return !string.IsNullOrEmpty(username);
        }
    }
}

MedicalQuestions/Controllers/HomeController.cs
using MedicalQuestions.Data;
using MedicalQuestions.Models;
using MedicalQuestions.Helpers;

using Microsoft.AspNetCore.Mvc;

using System.Diagnostics;

namespace MedicalQuestions.Controllers
{
    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            this.AttachUserDataToViewBag();

            return View();
        }

        public IActionResult Privacy()
        {
            this.AttachUserDataToViewBag();

            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MedicalQuestions/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;

namespace MedicalQuestions.Controllers
{
    public class QuestionController : BaseController
    {
        public IActionResult Index()
        {
            this.AttachUserDataToViewBag();

            return View();
        }
    }
}

MedicalQuestions/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MedicalQuestions/Views/Question/Index.cshtml
@{
    ViewData["Title"] = "Въпроси и отговори";
    bool isUserLoggedIn = ViewBag.IsUserLoggedIn ?? false;
}

<h1>
    Въпроси и отговори
</h1>

@if (!isUserLoggedIn)
{
    <h2>
        За да задавате въпроси е необходимо да направите безплатна регистрация
        <a asp-controller="Auth" asp-action="SignUp">тук</a>
    </h2>
}
else
{
    <h2>Not implemented yet.</h2>
}

MedicalQuestions/Views/Shared/_Layout.cshtml
@{
    bool isUserLoggedIn = ViewBag.IsUserLoggedIn ?? false;
    string userRole = ViewBag.UserRole;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MedicalQuestions</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MedicalQuestions.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MedicalQuestions</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Question" asp-action="Index">Въпроси и отговори</a>
                        </li>
                        @if (isUserLoggedIn)
                        {
                            if (userRole == "admin")
                            {
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">
                                        Администраторски панел
                                    </a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">
                                    Изход
                                </a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">
                                    Вход
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MedicalQuestions - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>